---
title: "Arnaud Natal"
description: |
 **Ph.D. Candidate in Economics** <br>
 <br>
 Research interest: *Microeconomics, household surveys, development economics, household finances, behavioural economics.* <br>
 <br>
 .pdf version [here](https://www.ifpindia.org/media/images/home-slide1-entrance.original.jpg)
   
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---



## Professional experience

**Research assistant** | French National Research Institute for Sustainable Development, India | 2022 - 2023

**Temporary lecturer and research assistant** | University of Bordeaux, France | 2021 - 2022

**Research assistant** | French Institute of Pondicherry, India | 2019

**Survey coordinator** | NGO FAGAD, Togo | 2018







## Affiliations

**French Institute of Pondicherry** | 2022 - .

**Bordeaux School of Economics** | 2019 - .









## Education

**Ph.D. in Economics** | University of Bordeaux, France | 2023

- Long  term stay at French Institute of Pondicherry, India
- Visiting at Newcastle University Business School, UK
- Visiting at LEDa-DIAL, France

**M.A. in Development Economics and Applied Statistics** | University of Bordeaux, France | 2019

**B.A. in Economics and Management** | University of Bordeaux, France | 2017









## Research

### Publications in peer-reviewed journals

1. Locus of Control, Social Identity, and Indebtedness in South India. *Revue d'Économie du Développement*, with C.J. Nordman. (2023).
1. Surviving Debt, Survival Debt in Times of Lockdown. *Economic & Political Weekly, 57*(1), 41–49, with I. Guérin, S. Michiels, C.J. Nordman, & G. Venkatasubramanian, G. (2022).  Full article available [here.](https://www.researchgate.net/publication/357617209_Surviving_Debt_and_Survival_Debt_in_Times_of_Lockdown)



### In progress

1. *Psychology of Debt in Rural Tamil Nadu, India*, with C.J. Nordman.
1. *Measure and (In)stability Over Time of Cognitive Skills and Personality Traits in Rural India*, with C.J. Nordman.
1. *Measuring household financial vulnerability in a poor developing area context: A new index and an application from rural South India*.
1. *Household Financial Vulnerability and Labour Supply in Rural South India*.
1. *The Political and Sexual Economies of Marriages: Two Decades of change in South-Arcot, South India*, with I. Guérin, C.J. Nordman & G. Venkatasubramanian.
1. *Ten years of labour, migration and debt in India: Insights from original longitudinal household surveys in Tamil Nadu*, with M. Di Santolo, I. Guérin, S. Michiels, C. Mouchel, C.J. Nordman & G. Venkatasubramanian.







## Data

#### Network Employment dEbt, Mobilities and Skills in south Indian Survey (NEEMSIS)

NEEMSIS is a socio-economic panel survey conducted in rural Tamil Nadu with two data points: 2016-17 and 2020-21. The NEEMSIS survey aim at understanding the links between labour, skills, social and migration dynamics and social networks formation in India. It explores how the formation of skills and social networks, especially those defined at the community and individual levels, influence observed inequalities in individuals’ trajectories in terms of social status (class, caste, gender, ethnicity, religion), employment and migration. This includes the investigation of various forces at play, spanning from the role of social structure (norms and institutions), the development and use of social networks, to the formation of cognitive and non-cognitive skills.

You can find more information on the [NEEMSIS survey website](https://neemsis.hypotheses.org/).

#### RUral Microfinance and Employment survey (RUME)

RUME survey is a socio-economic survey conducted in rural Tamil Nadu in 2010, in 10 villages and 405 households. The main objective was to explore the linkages between rural finance and rural employment – including diversification and migration – with a view to contributing to the ongoing discussions and interventions in the fields of rural development and poverty and vulnerability reduction.

You can find more information on the [RUME website](https://odriis.hypotheses.org/rume).









## Conferences

- ICDE conference, Clermont Auvergne University, France | 2022
- Challine conference, Aix-Marseille University, France | 2022
- DIAL seminar, LEDA-DIAL, France | 2022







## Teaching experiences

### Tutorials

- **Econometrics with R** (75h), B.A. level, University of Bordeaux | 2021 - 2022
- **Programming with Python** (21h), B.A. level, University of Bordeaux | 2021 - 2022
- **Microeconomics** (13.5h), B.A. level, University of Bordeaux | 2020 - 2021
- **Statistics** (54h), B.A. level, University of Bordeaux | 2020 - 2021

### Miscellaneous

- Trainer for the sixth **Social Sciences Winter School in Pondicherry** on the topic of Rethinking inequalities | 2022








## Activities

- Co-organiser of the internal seminar of the French Institute of Pondicherry | 2023
- Administrator of the website of the [Observatory of Rural Dynamics and Inequalities in South India](https://odriis.hypotheses.org/) | 2022 - .
- Administrator of the [NEEMSIS](https://odriis.hypotheses.org/) website | 2022 - .
- Member of the French Association of Development Economics ([AFEDEV](https://afedev.fr/)) | 2022 - .










## Skills

### Statistics

Excellent knowledge of **Stata** for statistical and econometric analysis as well as for data cleaning and management.
Fairly proficient in **R** and beginner in **Python**.

### Typesetting

Very good knowledge of **TeX** and **Markdown**.

### Miscellaneous

Good knowledge of **XLSForm** to code questionnaires and good knowledge of SurveyCTO and Kobotoolbox for deployment.

Proficient in **Gephi** for the graphic representation of networks.

Beginners in geographic information systems, with **QGIS**.

Good knowledge of the **Office** suite.

### Languages

**French** is my mother tongue and I have an advanced intermediate level in **English**.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


```

